USOFT/Areas/InformationTechnology/Controllers/MasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using USOFT.DataAccess.General;
using USOFT.DataAccess.Departement;
using USOFT.DataAccess.Currency;
using USOFT.DataAccess.Branch;
using USOFT.DataAccess.Measurement;
using USOFT.DataAccess.Upload;
using USOFT.DataAccess.IT;
using USOFT.Models;
using USOFT.DataAccess;

namespace USOFT.Areas.InformationTechnology.Controllers
{
    public class MasterController : Controller
    {
        //
        // GET: /InformationTechnology/Master/
        PopulatedDdl pop = new PopulatedDdl();
        MainITModel itmod = new MainITModel();
        ITMainModel it = new ITMainModel();
        public void isActive()
        {
            ViewBag.IsActive = new SelectList(pop.ActiveStateToCombo()).AsEnumerable();
        }
        public ActionResult Index()
        {
            return View();
        }
        public void populatedItemType(string id)
        {
            ViewBag.menu = new SelectList(pop.getMenu(id, "").AsEnumerable(), "ParamField", "ParamName");
        }
        public void populatedProblemType(string id)
        {
            ViewBag.menu = new SelectList(pop.getMenu(id, "").AsEnumerable(), "ParamField", "ParamName");
        }
        public void populatedSupplierType(string id)
        {
            ViewBag.menu = new SelectList(pop.getMenu(id, "").AsEnumerable(), "ParamField", "ParamName");
        }
        public void populatedConditionType(string id)
        {
            ViewBag.menu = new SelectList(pop.getMenu(id, "").AsEnumerable(), "ParamField", "ParamName");
        }
        public ActionResult ItemType(string id)
        {
            Usoft.Common.CommonFunction.CekSession.validate();
            if (Usoft.Common.CommonFunction.CekSession.validate() == true)
            {
                List<spGetUserInfo_Result> result = new List<spGetUserInfo_Result>();
                CekPriv cekpriv = new CekPriv();
                result = cekpriv.privilege(id);
                ViewData["Privilege"] = result;
                ViewBag.menuId = id;
            populatedItemType(id);
            return View();
                 }
            else
                return RedirectToAction("LogOut", "Account", new { area = "" });
        }
        public ActionResult ProblemType(string id)
        {
            Usoft.Common.CommonFunction.CekSession.validate();
            if (Usoft.Common.CommonFunction.CekSession.validate() == true)
            {
                List<spGetUserInfo_Result> result = new List<spGetUserInfo_Result>();
                CekPriv cekpriv = new CekPriv();
                result = cekpriv.privilege(id);
                ViewData["Privilege"] = result;
                ViewBag.menuId = id;
            populatedProblemType(id);
            return View();
                 }
            else
                return RedirectToAction("LogOut", "Account", new { area = "" });
        }
        public ActionResult SupplierList(string id)
        {
            Usoft.Common.CommonFunction.CekSession.validate();
            if (Usoft.Common.CommonFunction.CekSession.validate() == true)
            {
                List<spGetUserInfo_Result> result = new List<spGetUserInfo_Result>();
                CekPriv cekpriv = new CekPriv();
                result = cekpriv.privilege(id);
                ViewData["Privilege"] = result;
                ViewBag.menuId = id;
            populatedSupplierType(id);
            return View();
                 }
            else
                return RedirectToAction("LogOut", "Account", new { area = "" });
        }
        public ActionResult ITCondition(string id)
        {
            Usoft.Common.CommonFunction.CekSession.validate();
            if (Usoft.Common.CommonFunction.CekSession.validate() == true)
            {
                List<spGetUserInfo_Result> result = new List<spGetUserInfo_Result>();
                CekPriv cekpriv = new CekPriv();
                result = cekpriv.privilege(id);
                ViewData["Privilege"] = result;
                ViewBag.menuId = id;
                populatedConditionType(id);
                return View();
            }
            else
                return RedirectToAction("LogOut", "Account", new { area = "" });
        }
        [HttpPost]
        public JsonResult GetItemType(GetMenuResult ddl, string inputText, string sidx, string sord, int page, int rows)
        {
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;
            List<Object> obj = itmod.GetItemTypeList(inputText, ddl.ParamField, page, pageSize);
            var result = (List<spITItemType_Result>)obj[0];
            //"a.daris", "vch|UserId", 0 , " ", " ",page)
            int totalRecord = Convert.ToInt32(obj[2]);
            int totalPages = (int)Math.Ceiling((float)totalRecord / (float)pageSize);
            if (sord.ToUpper() == "DESC")
            {
                result = result.OrderByDescending(s => s.ItemTypeCode).ToList();
                //result = result.Skip(pageIndex * pageSize).Take(pageSize).ToList();
            }
            else
            {
                result = result.OrderBy(s => s.ItemTypeCode).ToList();
                //result = result.Skip(pageIndex * pageSize).Take(pageSize).ToList();
            }
            var jsonData = new
            {

                total = totalPages,
                page,
                records = totalRecord,
                rows = result
            };


            return Json(jsonData, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult GetProblemType(GetMenuResult ddl, string inputText, string sidx, string sord, int page, int rows)
        {
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;
            List<Object> obj = itmod.GetProblemTypeList(inputText, ddl.ParamField, page, pageSize);
            var result = (List<spITProblemTypeList_Result>)obj[0];
            //"a.daris", "vch|UserId", 0 , " ", " ",page)
            int totalRecord = Convert.ToInt32(obj[2]);
            int totalPages = (int)Math.Ceiling((float)totalRecord / (float)pageSize);
            if (sord.ToUpper() == "DESC")
            {
                result = result.OrderByDescending(s => s.ProblemTypeCode).ToList();
                //result = result.Skip(pageIndex * pageSize).Take(pageSize).ToList();
            }
            else
            {
                result = result.OrderBy(s => s.ProblemTypeCode).ToList();
                //result = result.Skip(pageIndex * pageSize).Take(pageSize).ToList();
            }
            var jsonData = new
            {

                total = totalPages,
                page,
                records = totalRecord,
                rows = result
            };


            return Json(jsonData, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult GetConditionType(GetMenuResult ddl, string inputText, string sidx, string sord, int page, int rows)
        {
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;
            List<Object> obj = itmod.getITConditionList(inputText, ddl.ParamField, page, pageSize);
            var result = (List<spITConditionList_Result>)obj[0];
            //"a.daris", "vch|UserId", 0 , " ", " ",page)
            int totalRecord = Convert.ToInt32(obj[2]);
            int totalPages = (int)Math.Ceiling((float)totalRecord / (float)pageSize);
            if (sord.ToUpper() == "DESC")
            {
                result = result.OrderByDescending(s => s.ConditionCode).ToList();
                //result = result.Skip(pageIndex * pageSize).Take(pageSize).ToList();
            }
            else
            {
                result = result.OrderBy(s => s.ConditionCode).ToList();
                //result = result.Skip(pageIndex * pageSize).Take(pageSize).ToList();
            }
            var jsonData = new
            {

                total = totalPages,
                page,
                records = totalRecord,
                rows = result
            };


            return Json(jsonData, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult GetSupplier(GetMenuResult ddl, string inputText, string sidx, string sord, int page, int rows)
        {
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;
            List<Object> obj = itmod.getITSupplierList(inputText, ddl.ParamField, page, pageSize);
            var result = (List<spITSupplierList_Result>)obj[0];
            //"a.daris", "vch|UserId", 0 , " ", " ",page)
            int totalRecord = Convert.ToInt32(obj[2]);
            int totalPages = (int)Math.Ceiling((float)totalRecord / (float)pageSize);
            if (sord.ToUpper() == "DESC")
            {
                result = result.OrderByDescending(s => s.SupplierCode).ToList();
                //result = result.Skip(pageIndex * pageSize).Take(pageSize).ToList();
            }
            else
            {
                result = result.OrderBy(s => s.SupplierCode).ToList();
                //result = result.Skip(pageIndex * pageSize).Take(pageSize).ToList();
            }
            var jsonData = new
            {

                total = totalPages,
                page,
                records = totalRecord,
                rows = result
            };


            return Json(jsonData, JsonRequestBehavior.AllowGet);

        }
        public ActionResult AddITITtemType(string id)
        {
            Usoft.Common.CommonFunction.CekSession.validate();
            if (Usoft.Common.CommonFunction.CekSession.validate() == true)
            {
                CekPriv cekpriv = new CekPriv();
                var result = cekpriv.privilege(id);

                if (result[0].CanInsert == true)
                {
                    ViewBag.menuId = id;

USOFT/Areas/Master/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using USOFT.DataAccess;
using USOFT.DataAccess.Users;
using USOFT.Models;
using USOFT.DataAccess.General;
using USOFT.DataAccess.Departement;
using USOFT.DataAccess.Currency;
using USOFT.DataAccess.Branch;
using USOFT.DataAccess.Measurement;
using USOFT.DataAccess.Upload;
using System.Collections;
using PagedList;
using System.Data.Entity.Core.Objects;
using Newtonsoft;


namespace USOFT.Areas.Master.Controllers
{
    public class BranchController : Controller
    {
        //
        // GET: /Master/Branch/
        Models.MainViewModels main = new Models.MainViewModels();
        PopulatedDdl ddl = new PopulatedDdl();
        USOFTEntities db = new USOFTEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Branch(string id)
        {
            Usoft.Common.CommonFunction.CekSession.validate();
            if (Usoft.Common.CommonFunction.CekSession.validate() == true)
            {
                List<spGetUserInfo_Result> result = new List<spGetUserInfo_Result>();
                CekPriv cekpriv = new CekPriv();
                result = cekpriv.privilege(id);
                ViewData["Privilege"] = result;
                ViewBag.menuId = id;
                PopulatedDdl dll = new PopulatedDdl();
                ViewBag.br = new SelectList(dll.brCombo().AsEnumerable(), "BranchId", "BranchName");
                ViewBag.menu = new SelectList(dll.getMenu(id, "").AsEnumerable(), "ParamField", "ParamName");
                return View();
            }
            else
                return RedirectToAction("Users");
          
        }
        [HttpPost]
        public JsonResult GetBranchData(GetMenuResult ddl, string searchvalue, string sidx, string sord, int rows, int page = 1)
        {
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;
            List<Object> obj = main.GetBranch(searchvalue, ddl.ParamField, page, pageSize);
            var result = (List<spBranchList_Result>)obj[0];
            int totalRecord = Convert.ToInt32(obj[2]);
            var totalPages = (int)Math.Ceiling((float)totalRecord / (float)pageSize);
            var jsonData = new
            {

                total = totalPages,
                page,
                records = totalRecord,
                rows = result.ToList()
            };

            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
        public ActionResult EditBranch(int value)
        {

            List<spBranchView_Result> branch = new List<spBranchView_Result>();
            BranchModel br = new BranchModel();
            branch = br.getBranchResult(value);
            ViewBag.brId = branch[0].BranchId;
            ViewBag.brName = branch[0].BranchName;
            ViewBag.brCode = branch[0].BranchCode;
            ViewBag.brAdd = branch[0].BranchAddress;
            ViewBag.brPhone = branch[0].BranchPhone;
            ViewBag.brType = new SelectList(ddl.branchType().AsEnumerable());
            ViewBag.brParent = new SelectList(ddl.brCombo().AsEnumerable(), "BranchId", "BranchName");
            ViewBag.active = new SelectList(ddl.ActiveStateToCombo().AsEnumerable());
            return View();
        }
        [HttpPost]
        public ActionResult editBranch(Branch br, string IsActive, string BranchType, int SearchValue,int? branchParent)
        {
            if (BranchType == "BRANCH")
            {
                branchParent = null;
            }
            bool active;
            if (IsActive == "Active")
            {
                active = true;
            }
            else
                active = false;
            int type;
            if (BranchType == "- SELECT ONE -")
            {
                type = 0;
            }
            else
                if (BranchType == "BRANCH")
                {
                    type = 1;
                }
                else
                    type = 2;
            BranchModel bra = new BranchModel();

            bra.editBranch(SearchValue, br.BranchCode, br.BranchName, type, branchParent, br.BranchAddress, br.BranchPhone, active, Session["UserId"].ToString());
            return RedirectToAction("EditBranch", "Branch", new {value = br.BranchId });
        }
        public ActionResult AddBranch(string id)
        {
            if (Usoft.Common.CommonFunction.CekSession.validate() == true)
            {
                CekPriv cekpriv = new CekPriv();
                var result = cekpriv.privilege(id);

                if (result[0].CanInsert == true)
                {
                    ViewBag.brType = new SelectList(ddl.branchType().AsEnumerable());
                    ViewBag.brParent = new SelectList(ddl.brCombo().AsEnumerable(), "BranchId", "BranchName");
                    ViewBag.active = new SelectList(ddl.ActiveStateToCombo().AsEnumerable());
                    ViewBag.menuId = id;
                    return View();
                }
                return RedirectToAction("LogOut", "Account", new { area = "" });
            }
            return RedirectToAction("LogOut", "Account", new { area = "" });
        }
        [HttpPost]
        public ActionResult addBranch(Branch br, string IsActive, string BranchType, int SearchValue, int? branchParent)
        {
            if (BranchType == "BRANCH")
            {
                branchParent = null;
            }
            bool active;
            if (IsActive == "Active")
            {
                active = true;
            }
            else
                active = false;
            int type;
            if (BranchType == "- SELECT ONE -")
            {
                type = 0;
            }
            else
                if (BranchType == "BRANCH")
                {
                    type = 1;
                }
                else
                    type = 2;
            BranchModel model = new BranchModel();
            model.insertBranch(SearchValue, br.BranchCode, br.BranchName, type, branchParent, br.BranchAddress, br.BranchPhone, active, Session["UserId"].ToString());
            return RedirectToAction("AddBranch", "Branch");

        }
    }
}

USOFT/Areas/InformationTechnology/Views/Master/AddITCondition.cshtml
@{
    ViewBag.Title = "AddITCondition";
}

@using (Html.BeginForm(FormMethod.Post))
{
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">ADD NEW CONDITION</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Add New Condition
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-8">

                            <form role="form">
                                <div class="form-group">
                                    @Html.Label("Condition Type Code", new { @class = "col-md-4 control-label" })

                                    <div class="col-lg-5">
                                        @*@Html.DropDownList("ParamField", (IEnumerable<SelectListItem>)ViewBag.menu, "All", new { @class = "form-control" })*@
                                        @Html.TextBox("piintConditionCode", null, new { @class = "form-control" })
                                    </div>

                                </div>
                                <div class="form-group">
                                    @Html.Label("Problem Type Name", new { @class = "col-md-4 control-label" })
                                    <div class="col-lg-5">
                                        @Html.TextBox("pivchConditionName", null, new { @class = "form-control" })
                                        @* @Html.DropDownList("BranchId", (SelectList)ViewBag.br, "All", new { @class = "form-control" })*@
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.Label("Active State", new { @class = "col-md-4 control-label" })
                                    <div class="col-lg-5">
                                        @Html.DropDownList("activeState", (SelectList)ViewBag.IsActive, "All", new { @class = "form-control" })
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            @*<input type="submit" value="Proses" id="buttonSearch" class="btn btn-default" />
                <input type="button" id="buttonCreate" value="Back" name="buttonAdd" class="btn btn-default" onclick="window.location.href('@Url.Action("Users","Users")')" />*@
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <input type="submit" value="Proses" id="buttonSearch" class="btn btn-default" />
                            <input type="button" id="buttonCreate" value="Back" name="buttonAdd" class="btn btn-default" onclick="window.location.href='@Url.Action("ITCondition", "Master", new {id = ViewBag.menuId })'" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@*@using (@Html.BeginForm(FormMethod.Post))
{
    <div id="container">
        <div class="div_common">
            @Html.Label("Condition Type Code")
            @Html.TextBox("piintConditionCode", null, new { @class = "input" })
            <p>
                @Html.Label("Problem Type Name")
                @Html.TextBox("pivchConditionName", null, new { @class = "input" })
            </p>
            @Html.Label("Active State")
            @Html.DropDownList("pibitIsActive", (SelectList)ViewBag.IsActive, "- Select One -", new { @class = "combobox" })
        </div>
    </div>
    <p><input type="Submit" value="Proses" class="buttonSub" id="buttonSearch" name="command" /></p>
}*@

USOFT/Areas/InformationTechnology/Views/Master/AddITITtemType.cshtml
@{
    ViewBag.Title = "AddITITtemType";
}
@using (Html.BeginForm(FormMethod.Post))
{
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">ADD NEW ITEM TYPE</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Add New Item Type
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-8">

                            <form role="form">
                                <div class="form-group">
                                    @Html.Label("Item Type Code", new { @class = "col-md-4 control-label" })

                                    <div class="col-lg-5">
                                        @*@Html.DropDownList("ParamField", (IEnumerable<SelectListItem>)ViewBag.menu, "All", new { @class = "form-control" })*@
                                        @Html.TextBox("pivchItemTypeCode", null, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.Label("Active State", new { @class = "col-md-4 control-label" })
                                    <div class="col-lg-5">
                                        @Html.DropDownList("activeState", (SelectList)ViewBag.IsActive, "All", new { @class = "form-control" })
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            @*<input type="submit" value="Proses" id="buttonSearch" class="btn btn-default" />
                <input type="button" id="buttonCreate" value="Back" name="buttonAdd" class="btn btn-default" onclick="window.location.href('@Url.Action("Users","Users")')" />*@
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <input type="submit" value="Proses" id="buttonSearch" class="btn btn-default" />
                            <input type="button" id="buttonCreate" value="Back" name="buttonAdd" class="btn btn-default" onclick="window.location.href='@Url.Action("ItemType", "Master", new { id = ViewBag.menuId })'" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@*<h2>AddITITtemType</h2>
@using (@Html.BeginForm(FormMethod.Post))
{
<div id="container">
    <div class="div_common">
        @Html.Label("Item Type Code")
        @Html.TextBox("pivchItemTypeCode", null, new { @class="input" })
        <p>
            @Html.Label("Item Type Name")
            @Html.TextBox("pivchItemTypeName", null, new { @class = "input" })
        </p>
        @Html.Label("Active State")
        @Html.DropDownList("piibitIsActive", (SelectList)ViewBag.IsActive, "- Select One -", new { @class="combobox" })
    </div>
</div>
<p><input type="Submit" value="Proses" class="buttonSub" id="buttonSearch" name="command" /></p>
}*@

USOFT/Areas/InformationTechnology/Views/Master/AddITProblemType.cshtml
@{
    ViewBag.Title = "AddITProblemType";
}
@using (Html.BeginForm(FormMethod.Post))
{
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">ADD IT PROBLEM TYPE</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Add New IT Problem Type
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-8">

                            <form role="form">
                                <div class="form-group">
                                    @Html.Label("Problem Type Code", new { @class = "col-md-4 control-label" })

                                    <div class="col-lg-5">
                                        @*@Html.DropDownList("ParamField", (IEnumerable<SelectListItem>)ViewBag.menu, "All", new { @class = "form-control" })*@
                                        @Html.TextBox("pivchProblemTypeCode", null, new { @class = "form-control" })
                                    </div>

                                </div>
                                <div class="form-group">
                                    @Html.Label("Problem Type Name", new { @class = "col-md-4 control-label" })

                                    <div class="col-lg-5">
                                        @*@Html.DropDownList("ParamField", (IEnumerable<SelectListItem>)ViewBag.menu, "All", new { @class = "form-control" })*@
                                        @Html.TextBox("pivchProblemTypeName", null, new { @class = "form-control" })
                                    </div>

                                </div>
                                <div class="form-group">
                                    @Html.Label("Active State", new { @class = "col-md-4 control-label" })
                                    <div class="col-lg-5">
                                        @Html.DropDownList("activeState", (SelectList)ViewBag.IsActive, "All", new { @class = "form-control" })
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            @*<input type="submit" value="Proses" id="buttonSearch" class="btn btn-default" />
                <input type="button" id="buttonCreate" value="Back" name="buttonAdd" class="btn btn-default" onclick="window.location.href('@Url.Action("Users","Users")')" />*@
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <input type="submit" value="Proses" id="buttonSearch" class="btn btn-default" />
                            <input type="button" id="buttonCreate" value="Back" name="buttonAdd" class="btn btn-default" onclick="window.location.href='@Url.Action("ProblemType", "Master", new { id = ViewBag.menuId })'" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@*<h2>AddITProblemType</h2>

@using (@Html.BeginForm(FormMethod.Post))
{
    <div id="container">
        <div class="div_common">
            @Html.Label("Problem Type Code")
            @Html.TextBox("pivchProblemTypeCode", null, new { @class = "input" })
            <p>
                @Html.Label("Problem Type Name")
                @Html.TextBox("pivchProblemTypeName", null, new { @class = "input" })
            </p>
            @Html.Label("Active State")
            @Html.DropDownList("piibitIsActive", (SelectList)ViewBag.IsActive, "- Select One -", new { @class = "combobox" })
        </div>
    </div>
    <p><input type="Submit" value="Proses" class="buttonSub" id="buttonSearch" name="command" /></p>
}*@

USOFT/Areas/InformationTechnology/Views/Master/EditITCondition.cshtml
@{
    ViewBag.Title = "EditITCondition";
}

@using (Html.BeginForm(FormMethod.Post))
{
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">UPDATE CONDITION TYPE</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Update Condition Type
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-8">

                            <form role="form">
                                <div class="form-group">
                                    @Html.Label("Condition Code", new { @class = "col-md-4 control-label" })
                                    <div class="col-lg-5">
                                        @*@Html.DropDownList("ParamField", (IEnumerable<SelectListItem>)ViewBag.menu, "All", new { @class = "form-control" })*@
                                        @Html.TextBox("piintConditionCode", (int)ViewBag.ConditionCode, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.Label("Condition Name", new { @class = "col-md-4 control-label" })
                                    <div class="col-lg-5">
                                        @*@Html.DropDownList("ParamField", (IEnumerable<SelectListItem>)ViewBag.menu, "All", new { @class = "form-control" })*@
                                        @Html.TextBox("pivchConditionName", (string)ViewBag.ConditionName, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.Label("Active State", new { @class = "col-md-4 control-label" })
                                    <div class="col-lg-5">
                                        @Html.DropDownList("activeState", (SelectList)ViewBag.IsActive, "All", new { @class = "form-control" })
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            @*<input type="submit" value="Proses" id="buttonSearch" class="btn btn-default" />
                <input type="button" id="buttonCreate" value="Back" name="buttonAdd" class="btn btn-default" onclick="window.location.href('@Url.Action("Users","Users")')" />*@
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <input type="submit" value="Proses" id="buttonSearch" class="btn btn-default" />
                            <input type="button" id="buttonCreate" value="Back" name="buttonAdd" class="btn btn-default" onclick="window.location.href('@Url.Action("ITCondition","Master")')" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}